name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: |
        cd /home/runner/work/
        git clone https://github.com/myWorldHub/GraphTest.git
        cp ./GraphConnectEngine/GraphConnectEngine/bin/Debug/GraphConnectEngine.dll ./GraphTest/GraphTest
        cd GraphTest
        dotnet test --no-build --verbosity normal
